### ISSUE TITLE
New Feature request 🆕

### ISSUE THREAD

**Issue by harsh-100** [ThisIsSahaj/AnCrypt#14]
As a user , Ancrypt is a good web app for me to checkout the crypto trends . And , by looking these cryptos make me excite to buy them . To separate the cryptos i want to buy ,it would be great if i can  keep them in my portfolio section which will show like -> "John's Porfolio " and it will all cryptos i have added there . 🎉

Along with that , it would be really helpful for me , if i can share my porfolio to my friend "Derek" who is a  financial advisor , he can see my porfolio i have created (as a secret i don't want to give him my login credential 🤫) . So , he can see my porfolio through a url something like -> "/portfolios/:userId" . Im the similar way i can see his porfolio . 

Thanks 😉
Will be exciting to see new feature in upcoming version ❤️

**Comment by ThisIsSahaj** [comment]
Hey there! I have already added a similar feature where you can add the crypto coins to your watchlist which is accessible from your profile. Note- You are required to sign in first before using the feature.

Portfolio sharing will be available soon !

Thankyou for your suggestions, they keep me motivated 😊

**Comment by ThisIsSahaj** [comment]
Hi there! The feature you requested has been implemented successfully 🎉

You can visit https://ancrypt.onrender.com/
- add some coins to your Portfolio
- Navigate to Portfolio section in header
- You will find a link to share your portfolio
- Share this link with your friends and they'll be able to view your Portfolio (but not edit it) 
😊

**Comment by harsh-100** [comment]
- porfolio is not visible in other persons accout , please look into it 
- although , you have done a great job in the adding porfolio section , i really appreatiate that 🎉😉
