### ISSUE TITLE
Consent regarding mobile view 📱

### ISSUE THREAD

**Issue by harsh-100** [ThisIsSahaj/AnCrypt#4]
As a user , this site is really helpful it would be great if you make a good mobile version of this website too. As of now , it is looking good in desktop, but i use mobile more so want to see the crypto trends obviously there 🧐 . 
Hope , to see the latest mobile version soon
Thanks ❤️

**Comment by ThisIsSahaj** [comment]
Thankyou for showing your consent. I have made the changes and now the complete website is all device friendly i.e. it is now completely responsive for mobiles and other screens. Thankyou for supporting :) You can visit the deployed website at https://ancrypt.onrender.com/
